import 'package:flutter/material.dart';
import 'package:flutter_kos/models.dart/models.dart';
import 'package:flutter_kos/models.dart/space.dart';
import 'package:flutter_kos/models.dart/tips.dart';
import 'package:flutter_kos/providers/space_provider.dart';
import 'package:flutter_kos/shared/theme.dart';
import 'package:flutter_kos/widgets/widgets.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';

part 'splash_page.dart';
part 'home_page.dart';
part 'detail_page.dart';
part 'error_page.dart';
part 'mainpage.dart';
part 'message_page.dart';
part 'card_page.dart';
part 'favorite_page.dart';
